core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("empresarios.urls")),
    path('', include("investidores.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

investidores/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sugestao/', views.sugestao, name="sugestao"),
    path('ver_empresa/<int:id>', views.ver_empresa, name="ver_empresa"),
    path('realizar_proposta/<int:id>', views.realizar_proposta, name="realizar_proposta"),
    path('assinar_contrato/<int:id>', views.assinar_contrato, name="assinar_contrato"),

]

empresarios/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.utils.safestring import mark_safe

# Create your models here.

class Empresas(models.Model):
    tempo_existencia_choices = (
        ('-6', 'Menos de 6 meses'),
        ('+6', 'Mais de 6 meses'),
        ('+1', 'Mais de 1 ano'),
        ('+5', 'Mais de 5 anos'),)
    estagio_choices = (
        ('I', 'Tenho apenas uma idea'),
        ('MVP', 'Possuo um MVP'),
        ('MVPP', 'Possuo um MVP com clientes pagantes'),
        ('E', 'Empresa pronta para escalar'),
        )
    area_choices = (
        ('ED', 'Ed-tech'),
        ('FT', 'Fintech'),
        ('AT', 'Agrotech'),    
        )

    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=50)
    cnpj = models.CharField(max_length=30)
    site = models.URLField()
    tempo_existencia = models.CharField(max_length=2, choices=tempo_existencia_choices, default='-6')
    descricao = models.TextField() 
    data_final_captacao = models.DateField()
    percentual_equity = models.IntegerField() # Percentual esperado
    estagio = models.CharField(max_length=4, choices=estagio_choices, default='I')
    area = models.CharField(max_length=3, choices=area_choices)
    publico_alvo = models.CharField(max_length=3)
    valor = models.DecimalField(max_digits=9, decimal_places=2) # Valor total a ser vendido
    pitch = models.FileField(upload_to='pitchs')
    logo = models.FileField(upload_to='logo')
    def __str__(self):
        return f'{self.user.username} | {self.nome}'
    
    @property
    def status(self):
        if date.today() > self.data_final_captacao :
            return mark_safe("<span class='bg-green-300 text-black font-bold px-4 py-1 rounded-lg'>Captação finalizada</span>")
        
        return mark_safe("<span class='bg-gray-700 font-bold px-4 py-1 rounded-lg'>Em Captação</span>")
    
    def valuation(self):
        return float(f"{(100 * self.valor) / self.percentual_equity:.2f}")
    
    
    
    
class Documento(models.Model):
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    arquivo = models.FileField(upload_to="documentos")

    def __str__(self):
        return self.titulo
    
    
class Metricas(models.Model):
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    valor = models.FloatField()

    def __str__(self):
        return self.titulo

investidores/models.py
from django.db import models
from empresarios.models import Empresas
from django.contrib.auth.models import User

# Create your models here.
class PropostaInvestimento(models.Model):
    status_choices = (
        ('AS', 'Aguardando assinatura'),
        ('PE', 'Proposta enviada'),
        ('PA', 'Proposta aceita'),
        ('PR', 'Proposta recusada')
    )
    valor = models.DecimalField(max_digits=9, decimal_places=2)
    percentual = models.FloatField()
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    investidor = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, choices=status_choices, default='AS')
    selfie = models.FileField(upload_to="selfie", null=True, blank=True)
    rg = models.FileField(upload_to="rg", null=True, blank=True)

    def __str__(self):
        return str(self.valor)

investidores/views.py
from django.shortcuts import render, redirect
from empresarios.models import Empresas, Documento
from .models import PropostaInvestimento
from django.contrib.messages import add_message, constants
from django.http import Http404

# Create your views here.
def sugestao(request):   
    areas = Empresas.area_choices
    if request.method == "GET":   
        return render(request, 'investidores/sugestao.html', {'areas': areas})
    elif request.method == "POST":
        tipo = request.POST.get('tipo')
        area = request.POST.getlist('area')
        valor = request.POST.get('valor')

        if tipo == 'C':
            empresas = Empresas.objects.filter(tempo_existencia='+5').filter(estagio="E")
        elif tipo == 'D':
            empresas = Empresas.objects.filter(tempo_existencia__in=['-6', '+6', '+1']).exclude(estagio="E")
        
        empresas = empresas.filter(area__in=area)
        
        empresas_selecionadas = []
        for empresa in empresas:
            percentual = (float(valor) * 100) / float(empresa.valuation())
            if percentual >= 1:
                empresas_selecionadas.append(empresa)

        return render(request, 'investidores/sugestao.html', {'empresas': empresas_selecionadas, 'areas': areas})


def ver_empresa(request, id):
    empresa = Empresas.objects.get(id=id)
    documentos = Documento.objects.filter(empresa=empresa)
    return render(request, 'investidores/ver_empresa.html', {'empresa': empresa, "documentos": documentos})


def realizar_proposta(request, id):
    valor = request.POST.get('valor')
    percentual = request.POST.get('percentual')
    empresa = Empresas.objects.get(id=id)

    propostas_aceitas = PropostaInvestimento.objects.filter(empresa=empresa).filter(status='PA')
    total = 0

    for pa in propostas_aceitas:
        total = total + pa.percentual

    if total + int(percentual)  > empresa.percentual_equity:
        add_message(request, constants.WARNING, 'O percentual solicitado ultrapassa o percentual máximo.')
        return redirect(f'/ver_empresa/{id}')


    valuation =  int(valor) * int(percentual) / 100
    print(valuation)

    if valuation < int(empresa.valuation())/2 :
        add_message(request, constants.WARNING, f'Seu valuation proposto foi R${valuation} e deve ser no mínimo R${empresa.valuation()/2}')
        return redirect(f'/ver_empresa/{id}')

    pi = PropostaInvestimento(
        valor = valor,
        percentual = percentual,
        empresa = empresa,
        investidor = request.user,
    )

    pi.save()

    #add_message(request, constants.SUCCESS, f'Proposta enviada com sucesso')
    return redirect(f'/assinar_contrato/{pi.id}')


def assinar_contrato(request, id):
    pi = PropostaInvestimento.objects.get(id=id)
    if pi.status != "AS":
        raise Http404()
    
    if request.method == "GET":
        return render(request, 'investidores/assinar_contrato.html', {'id': id})
    elif request.method == "POST":
        selfie = request.FILES.get('selfie')
        rg = request.FILES.get('rg')
        print(request.FILES)
        

        pi.selfie = selfie
        pi.rg = rg
        pi.status = 'PE'
        pi.save()

        add_message(request, constants.SUCCESS, f'Contrato assinado com sucesso, sua proposta foi enviada a empresa.')
        return redirect(f'/ver_empresa/{pi.empresa.id}')

investidores/templates/investidores/assinar_contrato.html
{% extends "empresarios/modelo.html" %}
#
{% load static %}

{% block title %}Assinar contrato{% endblock title %}

{% block titulo %}
    {% include "empresarios/navbar.html" %}
{% endblock titulo %}

{% block conteudo %}
    <br><br>
    <div class="container">
        <div class="flex-row">
            <div class="col-span-7">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="col-span-2">
                        <img src="{% static '/img/foto_perfil.webp' %}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-span-2">
                        <h3 class="text-4xl text-center text-violet-800">Assinar contrato</h3>
                    </div>
                </div>
            </div>
            <div  class="mt-10 p-5 text-white bg-gray-700 ">
                <h3>Contrato de investimento</h3>
                <p>Ao assinar esse contrato você concorda com todas as cláusulas abaixo</p>

                <ol>
                    <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                    <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                    <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                </ol>

            </div>
            <form action="{% url 'assinar_contrato' id %}" enctype='multipart/form-data' method="POST" style="margin-top: 20px;"> {% csrf_token %}
                <input type="file" name="selfie" class="w-9/12 m-4 hover:ring-1" >
                <br>
                <input type="file" name="rg" class="w-9/12 m-4 hover:ring-1">
                <br>
                <div class="text-center">
                    <input type="submit" class="hover:bg-green-400 text-black hover:text-white bg-green-300 rounded-lg px-4 py-2" value="Assinar contrato">
                </div>
            </form>
        </div>
        <br><br>
{% endblock conteudo %}

{% block footer %}{% endblock footer %}
{% block scritps %}{% endblock scritps %}

investidores/templates/investidores/copi.html
{% extends "empresarios/modelo.html" %}
#
{% load static %}

{% block title %}Copia html{% endblock title %}
{% block nav %}{% endblock nav %}
{% block titulo %}
    {% include "empresarios/navbar.html" %}
    <h1 class="text-center text-4xl text-violet-500">Pagina copia</h1>
{% endblock titulo %}
{% block conteudo %}


{% endblock conteudo %}
{% block footer %}{% endblock footer %}
{% block scritps %}{% endblock scritps %}

investidores/templates/investidores/sugestao.html
{% extends "empresarios/modelo.html" %}
#
{% load static %}

{% block title %}Empresa{% endblock title %}
{% block nav %}{% endblock nav %}
{% block titulo %}
    {% include "empresarios/navbar.html" %}
    <h1 class="text-center text-4xl text-violet-500">Pagina sugestao</h1>
{% endblock titulo %}
{% block conteudo %}
    <br><br>
    <div class="mx-36">
        <div class="text-center">
            <h2 class="text-white text-4xl">Receba sugestões de empresas</h2>
            <p class="text-sm text-violet-500">Vamos analisar seu perfil e indicar as melhores opções de investimentos</p>
        </div>
        <br>
        <div class="bg-green-600-800 text-white p-4">
            <h3>Tipo de investidor</h3>
            <div class="w-[60%] text-sm">
                <form action="{% url 'sugestao' %}" method="POST">{% csrf_token %}
                    <p class="text-violet-500">Selecione conservador caso busque investimentos de menos risco
                        e com menor retorno, selecione despojado se prefere correr mais riscos
                        e ter maiores possíbilidades de retorno.</p>
                    <select name="tipo" id="" class="bg-gray-200 font-semibold text-purple-400 w-96 my-2 py-2 px-4">
                        <option value="C">Conservador</option>
                        <option value="D">Despojado</option>
                    </select>
                    <br>
                    <h3>Áreas de interesses</h3>
                    <p>Selecione as áreas de mercado que possui interesse em investir</p>
                    <select name="area" id="" class="bg-gray-200 font-semibold text-purple-400 w-96 my-2 py-2 px-4 rounded-lg" multiple>
                        {% for area in areas %}
                            <option value="{{area.0}}">{{area.1}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <h3>Valor que deseja investir</h3>
                    <p>Coloque o valor máximo que deseja investir</p>
                    <input type="number" name="valor" class="text-gray-700 font-semibold px-4 py-2 rounded-lg my-4 w-[400px]" placeholder="00,00">
                    <br>
                    <input type="submit" class="ring-2  ring-gray-100 hover:ring-green-300  text-sky-500 font-bold w-[400px] hover:bg-sky-500 hover:text-black px-4 py-2 rounded-lg">
                </form>
            </div>
        </div>
        <br>
        <br>
        <div class="row">
            {% for empresa in empresas %}
                <div class="col-md">
                    <div class="card dark-color" style="width: 18rem; border: none;" >
                        <img class="card-img-top dark-color" src="{{empresa.logo.url}}" alt="Card image cap">
                        <div class="card-body dark-color">
                            <h5 class="card-title">{{empresa.nome}}</h5>
                            <p class="card-text">{{empresa.descricao}}</p>
                            <a href="{% url 'ver_empresa' empresa.id %}" class="btn btn-indigo">Acessar</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock conteudo %}
{% block footer %}{% endblock footer %}
{% block scritps %}{% endblock scritps %}

investidores/templates/investidores/ver_empresa.html
{% extends "empresarios/modelo.html" %}
#
{% load static %}

{% block title %}Ver Empresa{% endblock title %}

{% block nav %}{% endblock nav %}

{% block titulo %}{% endblock titulo %}

{% block conteudo %}
    {% include "empresarios/navbar.html" %}
    <h1 class="text-center text-4xl text-violet-500">Ver Empresas</h1>
    <br><br>
    <div class="mx-16">
        <div class="flex ">
            <div class="">
                <div class="col-span-2">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="flex flex-row px-8">
                        <div class="col-span-1 me-4">
                            <img src="{{empresa.logo.url}}" class="w-32" alt="">
                        </div>
                        <div class="col-span-2 ms-4">
                            <h3 class="text-4xl text-gray-300 font-semibold">{{empresa.nome}}</h3>
                            <span class=" px-4 ring-2 m-4 rounded-lg text-sm">{{empresa.get_area_display}}</span>
                        </div>
                    </div>
                </div>
                <br>
                <div class="progress rounded-lg" style="height: 1% ;background: #fff; ">
                    <div class="progress-bar bg-sky-300"
                         style="width: 30% ; background: green;"></div>
                    <div class="progress-bar bg-green-300"
                         style="width: 40%;"></div>
                </div>
                <br>

                <div class="flex flex-row">

                    <span class="px-4 ring-4 text-sm rounded-lg text-green-400 font-semibold w-12/12">&nbsp &nbsp A empresa já atingiu 80% do percentual captado, portanto seu investimento será concretizado.</span>

                </div>
                   <!--  <span class="badge bg-warning">x</span><span>&nbsp &nbsp Seu investimento será concretizado caso a empresa atinja pelo meno 80% do valor esperado até a data final.</span>-->

                <hr class="my-4">
                <p>{{empresa.descricao}}</p>
                <div class="col-md">
                    <h5>Valuation esperado</h5>
                    <span class="sub-fonte">Esperado: {{empresa.valuation}}</span>
                    <br>
                    <br>
                    <h5>Percentual</h5>
                    <span class="sub-fonte">Total a venda: {{empresa.percentual_equity}}%</span>
                    <br>
                    <span class="sub-fonte">Disponivel à compra: %</span>
                </div>
                <br>
                <span class="badge bg-warning">{{empresa.publico_alvo}}</span>
                <br><br>
                <h4 style="color: #92D5EB">Indicadores |</h4>
                <div class="flex justify-between">
                    <div class="col-span-4" >
                        <div class="text-gray-300 p-5 text-center">
                            <h5>CAC</h5>
                            <h6>R$ 200</h6>
                        </div>
                    </div>
                    <div class="col-span-1" >
                        <div class="text-gray-300 p-5 text-center" >
                            <h5>CAC</h5>
                            <h6>R$ 200</h6>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="flex flex-row">
                    <h4>Faça sua proposta</h4>
                    <br><br>
                    <div class="col-span-1 mx-4">
                        <form action="{% url 'realizar_proposta' empresa.id %}" method="POST"> {% csrf_token %}
                            <input type="number" name="valor" class="form-control" placeholder="Valor para investir">
                            <br>
                            <input type="submit" class="bg-indigo-400 px-4 py-2 hover:bg-indigo-300 ring-2 hover:ring-green-200 rounded-lg text-gray-700 hover:text-black hover:font-bold" value="Salvar">
                        </div>
                        <div class="col-span-1 mx-4">
                            <input type="number" name="percentual" class="form-control" placeholder="Percentual desejado">
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-5 intereses-investimentos">
                <video name='demo' controls autoplay width='100%'>
                    <source src="{{empresa.pitch.url}}" type="video/mp4"></source>
                </video>
                <hr>
                {% for doc in documentos %}
                    <div class="list_documentos flex">
                        <div class="flex-row w-full bg-gray-700 rounded-md">
                            <div class=" " >
                                <a href='{{ doc.arquivo.url }}'>
                                    <img class="w-8 ps-2 py-2 rounded-sm" src="{% static "img/download.png" %}" alt="logo download" title="download" >
                                </a>
                            </div>
                            <div class="col-span-1">{{doc.titulo}}</div>
                {% endfor %}
                <div class="col-span-1" style="text-align: right;"></div>
            </div>
        </div>
    </div>
    </div>
    </div>
    <br><br>
{% endblock conteudo %}

{% block footer %}{% endblock footer %}
{% block scritps %}{% endblock scritps %}